In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 250.2 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.9 MB 250.2 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.9 MB 250.2 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.9 MB 250.2 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.9 MB 250.2 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.9 MB 250.2 kB/s eta 0:00:38
   -- ------------------------------------- 0.5/9.9 MB 250.2 kB/s eta 0:00:38
   --- ------------------------------------ 0.8/9.9 MB 212.9 kB/s eta 0:00:43
   --- ------------------------------------ 0.8/9.9 MB 212.9 kB/s eta 0:00:43
   --- ------------------------------------ 0.8/9.9 MB 212.9 kB/s eta 0:00:43
   --- ------------------------------------ 0.8/9.9 MB 212.9 kB/s eta 0:00:43
   --- ------------------------------------ 0.8/9.9 MB 212.9 kB/s eta 0:00:43
   --- ------------------------------------ 0.8/9.9 MB 212.9 kB/s eta 0:00:43
   --- ------------------------------------ 0.8/9.9 MB 212.9 kB/s eta 0:00:43
   ---- ----------------------------------- 1.0/9.9 MB 206.5 kB/s eta 0:00:43
   ---- ----------------------------------- 1.0/9.9 MB 206.5 kB/s eta 0:00:43
   ---- ----------------------------------- 1.0/9.9 MB 206.5 kB/s eta 0:00:43
   ---- ----------------------------------- 1.0/9.9 MB 206.5 kB/s eta 0:00:43
   ---- ----------------------------------- 1.0/9.9 MB 206.5 kB/s eta 0:00:43
   ---- ----------------------------------- 1.0/9.9 MB 206.5 kB/s eta 0:00:43
   ---- ----------------------------------- 1.0/9.9 MB 206.5 kB/s eta 0:00:43
   ----- ---------------------------------- 1.3/9.9 MB 195.7 kB/s eta 0:00:44
   ----- ---------------------------------- 1.3/9.9 MB 195.7 kB/s eta 0:00:44
   ----- ---------------------------------- 1.3/9.9 MB 195.7 kB/s eta 0:00:44
   ----- ---------------------------------- 1.3/9.9 MB 195.7 kB/s eta 0:00:44
   ----- ---------------------------------- 1.3/9.9 MB 195.7 kB/s eta 0:00:44
   ----- ---------------------------------- 1.3/9.9 MB 195.7 kB/s eta 0:00:44
   ----- ---------------------------------- 1.3/9.9 MB 195.7 kB/s eta 0:00:44
   ----- ---------------------------------- 1.3/9.9 MB 195.7 kB/s eta 0:00:44
   ----- ---------------------------------- 1.3/9.9 MB 195.7 kB/s eta 0:00:44
   ------ --------------------------------- 1.6/9.9 MB 179.9 kB/s eta 0:00:47
   ------ --------------------------------- 1.6/9.9 MB 179.9 kB/s eta 0:00:47
   ------ --------------------------------- 1.6/9.9 MB 179.9 kB/s eta 0:00:47
   ------ --------------------------------- 1.6/9.9 MB 179.9 kB/s eta 0:00:47
   ------ --------------------------------- 1.6/9.9 MB 179.9 kB/s eta 0:00:47
   ------- -------------------------------- 1.8/9.9 MB 190.1 kB/s eta 0:00:43
   ------- -------------------------------- 1.8/9.9 MB 190.1 kB/s eta 0:00:43
   ------- -------------------------------- 1.8/9.9 MB 190.1 kB/s eta 0:00:43
   ------- -------------------------------- 1.8/9.9 MB 190.1 kB/s eta 0:00:43
   ------- -------------------------------- 1.8/9.9 MB 190.1 kB/s eta 0:00:43
   ------- -------------------------------- 1.8/9.9 MB 190.1 kB/s eta 0:00:43
   ------- -------------------------------- 1.8/9.9 MB 190.1 kB/s eta 0:00:43
   ------- -------------------------------- 1.8/9.9 MB 190.1 kB/s eta 0:00:43
   ------- -------------------------------- 1.8/9.9 MB 190.1 kB/s eta 0:00:43
   -------- ------------------------------- 2.1/9.9 MB 182.3 kB/s eta 0:00:43
   -------- ------------------------------- 2.1/9.9 MB 182.3 kB/s eta 0:00:43
   -------- ------------------------------- 2.1/9.9 MB 182.3 kB/s eta 0:00:43
   -------- ------------------------------- 2.1/9.9 MB 182.3 kB/s eta 0:00:43
   -------- ------------------------------- 2.1/9.9 MB 182.3 kB/s eta 0:00:43
   -------- ------------------------------- 2.1/9.9 MB 182.3 kB/s eta 0:00:43
   -------- ------------------------------- 2.1/9.9 MB 182.3 kB/s eta 0:00:43
   -------- ------------------------------- 2.1/9.9 MB 182.3 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.9 MB 178.3 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.9 MB 178.3 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.9 MB 178.3 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.9 MB 178.3 kB/s eta 0:00:43
   --------- ------------------------------ 2.4/9.9 MB 178.3 kB/s eta 0:00:43
   ---------- ----------------------------- 2.6/9.9 MB 184.4 kB/s eta 0:00:40
   ---------- ----------------------------- 2.6/9.9 MB 184.4 kB/s eta 0:00:40
   ---------- ----------------------------- 2.6/9.9 MB 184.4 kB/s eta 0:00:40
   ---------- ----------------------------- 2.6/9.9 MB 184.4 kB/s eta 0:00:40
   ---------- ----------------------------- 2.6/9.9 MB 184.4 kB/s eta 0:00:40
   ---------- ----------------------------- 2.6/9.9 MB 184.4 kB/s eta 0:00:40
   ----------- ---------------------------- 2.9/9.9 MB 185.7 kB/s eta 0:00:38
   ----------- ---------------------------- 2.9/9.9 MB 185.7 kB/s eta 0:00:38
   ----------- ---------------------------- 2.9/9.9 MB 185.7 kB/s eta 0:00:38
   ----------- ---------------------------- 2.9/9.9 MB 185.7 kB/s eta 0:00:38
   ----------- ---------------------------- 2.9/9.9 MB 185.7 kB/s eta 0:00:38
   ----------- ---------------------------- 2.9/9.9 MB 185.7 kB/s eta 0:00:38
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------ --------------------------- 3.1/9.9 MB 188.5 kB/s eta 0:00:36
   ------------- -------------------------- 3.4/9.9 MB 174.0 kB/s eta 0:00:38
   ------------- -------------------------- 3.4/9.9 MB 174.0 kB/s eta 0:00:38
   ------------- -------------------------- 3.4/9.9 MB 174.0 kB/s eta 0:00:38
   ------------- -------------------------- 3.4/9.9 MB 174.0 kB/s eta 0:00:38
   ------------- -------------------------- 3.4/9.9 MB 174.0 kB/s eta 0:00:38
   ------------- -------------------------- 3.4/9.9 MB 174.0 kB/s eta 0:00:38
   ------------- -------------------------- 3.4/9.9 MB 174.0 kB/s eta 0:00:38
   -------------- ------------------------- 3.7/9.9 MB 174.9 kB/s eta 0:00:36
   -------------- ------------------------- 3.7/9.9 MB 174.9 kB/s eta 0:00:36
   -------------- ------------------------- 3.7/9.9 MB 174.9 kB/s eta 0:00:36
   -------------- ------------------------- 3.7/9.9 MB 174.9 kB/s eta 0:00:36
   -------------- ------------------------- 3.7/9.9 MB 174.9 kB/s eta 0:00:36
   --------------- ------------------------ 3.9/9.9 MB 179.3 kB/s eta 0:00:34
   --------------- ------------------------ 3.9/9.9 MB 179.3 kB/s eta 0:00:34
   --------------- ------------------------ 3.9/9.9 MB 179.3 kB/s eta 0:00:34
   --------------- ------------------------ 3.9/9.9 MB 179.3 kB/s eta 0:00:34
   --------------- ------------------------ 3.9/9.9 MB 179.3 kB/s eta 0:00:34
   --------------- ------------------------ 3.9/9.9 MB 179.3 kB/s eta 0:00:34
   --------------- ------------------------ 3.9/9.9 MB 179.3 kB/s eta 0:00:34
   ----------------- ---------------------- 4.2/9.9 MB 179.1 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.9 MB 179.1 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.9 MB 179.1 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.9 MB 179.1 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.9 MB 179.1 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.9 MB 179.1 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.9 MB 179.1 kB/s eta 0:00:32
   ----------------- ---------------------- 4.2/9.9 MB 179.1 kB/s eta 0:00:32
   ------------------ --------------------- 4.5/9.9 MB 177.7 kB/s eta 0:00:31
   ------------------ --------------------- 4.5/9.9 MB 177.7 kB/s eta 0:00:31
   ------------------ --------------------- 4.5/9.9 MB 177.7 kB/s eta 0:00:31
   ------------------- -------------------- 4.7/9.9 MB 183.3 kB/s eta 0:00:29
   ------------------- -------------------- 4.7/9.9 MB 183.3 kB/s eta 0:00:29
   ------------------- -------------------- 4.7/9.9 MB 183.3 kB/s eta 0:00:29
   ------------------- -------------------- 4.7/9.9 MB 183.3 kB/s eta 0:00:29
   -------------------- ------------------- 5.0/9.9 MB 188.3 kB/s eta 0:00:26
   -------------------- ------------------- 5.0/9.9 MB 188.3 kB/s eta 0:00:26
   -------------------- ------------------- 5.0/9.9 MB 188.3 kB/s eta 0:00:26
   --------------------- ------------------ 5.2/9.9 MB 193.4 kB/s eta 0:00:24
   --------------------- ------------------ 5.2/9.9 MB 193.4 kB/s eta 0:00:24
   --------------------- ------------------ 5.2/9.9 MB 193.4 kB/s eta 0:00:24
   ---------------------- ----------------- 5.5/9.9 MB 198.9 kB/s eta 0:00:22
   ---------------------- ----------------- 5.5/9.9 MB 198.9 kB/s eta 0:00:22
   ---------------------- ----------------- 5.5/9.9 MB 198.9 kB/s eta 0:00:22
   ---------------------- ----------------- 5.5/9.9 MB 198.9 kB/s eta 0:00:22
   ----------------------- ---------------- 5.8/9.9 MB 202.5 kB/s eta 0:00:21
   ----------------------- ---------------- 5.8/9.9 MB 202.5 kB/s eta 0:00:21
   ----------------------- ---------------- 5.8/9.9 MB 202.5 kB/s eta 0:00:21
   ----------------------- ---------------- 5.8/9.9 MB 202.5 kB/s eta 0:00:21
   ------------------------ --------------- 6.0/9.9 MB 206.3 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.9 MB 206.3 kB/s eta 0:00:19
   ------------------------ --------------- 6.0/9.9 MB 206.3 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.9 MB 210.2 kB/s eta 0:00:18
   ------------------------- -------------- 6.3/9.9 MB 210.2 kB/s eta 0:00:18
   ------------------------- -------------- 6.3/9.9 MB 210.2 kB/s eta 0:00:18
   ------------------------- -------------- 6.3/9.9 MB 210.2 kB/s eta 0:00:18
   ------------------------- -------------- 6.3/9.9 MB 210.2 kB/s eta 0:00:18
   -------------------------- ------------- 6.6/9.9 MB 211.5 kB/s eta 0:00:16
   -------------------------- ------------- 6.6/9.9 MB 211.5 kB/s eta 0:00:16
   -------------------------- ------------- 6.6/9.9 MB 211.5 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 215.0 kB/s eta 0:00:15
   --------------------------- ------------ 6.8/9.9 MB 215.0 kB/s eta 0:00:15
   --------------------------- ------------ 6.8/9.9 MB 215.0 kB/s eta 0:00:15
   --------------------------- ------------ 6.8/9.9 MB 215.0 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 218.5 kB/s eta 0:00:13
   ---------------------------- ----------- 7.1/9.9 MB 218.5 kB/s eta 0:00:13
   ---------------------------- ----------- 7.1/9.9 MB 218.5 kB/s eta 0:00:13
   ---------------------------- ----------- 7.1/9.9 MB 218.5 kB/s eta 0:00:13
   ----------------------------- ---------- 7.3/9.9 MB 222.2 kB/s eta 0:00:12
   ----------------------------- ---------- 7.3/9.9 MB 222.2 kB/s eta 0:00:12
   ----------------------------- ---------- 7.3/9.9 MB 222.2 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.9 MB 226.5 kB/s eta 0:00:10
   ------------------------------ --------- 7.6/9.9 MB 226.5 kB/s eta 0:00:10
   ------------------------------ --------- 7.6/9.9 MB 226.5 kB/s eta 0:00:10
   ------------------------------- -------- 7.9/9.9 MB 230.7 kB/s eta 0:00:09
   ------------------------------- -------- 7.9/9.9 MB 230.7 kB/s eta 0:00:09
   ------------------------------- -------- 7.9/9.9 MB 230.7 kB/s eta 0:00:09
   ------------------------------- -------- 7.9/9.9 MB 230.7 kB/s eta 0:00:09
   ------------------------------- -------- 7.9/9.9 MB 230.7 kB/s eta 0:00:09
   ------------------------------- -------- 7.9/9.9 MB 230.7 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 234.5 kB/s eta 0:00:08
   -------------------------------- ------- 8.1/9.9 MB 234.5 kB/s eta 0:00:08
   -------------------------------- ------- 8.1/9.9 MB 234.5 kB/s eta 0:00:08
   -------------------------------- ------- 8.1/9.9 MB 234.5 kB/s eta 0:00:08
   -------------------------------- ------- 8.1/9.9 MB 234.5 kB/s eta 0:00:08
   ---------------------------------- ----- 8.4/9.9 MB 241.6 kB/s eta 0:00:07
   ---------------------------------- ----- 8.4/9.9 MB 241.6 kB/s eta 0:00:07
   ---------------------------------- ----- 8.4/9.9 MB 241.6 kB/s eta 0:00:07
   ---------------------------------- ----- 8.4/9.9 MB 241.6 kB/s eta 0:00:07
   ---------------------------------- ----- 8.4/9.9 MB 241.6 kB/s eta 0:00:07
   ---------------------------------- ----- 8.4/9.9 MB 241.6 kB/s eta 0:00:07
   ---------------------------------- ----- 8.4/9.9 MB 241.6 kB/s eta 0:00:07
   ----------------------------------- ---- 8.7/9.9 MB 238.0 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.9 MB 238.0 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.9 MB 238.0 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.9 MB 238.0 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.9 MB 238.0 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.9 MB 238.0 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.9 MB 238.0 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.9 MB 238.0 kB/s eta 0:00:06
   ----------------------------------- ---- 8.7/9.9 MB 238.0 kB/s eta 0:00:06
   ------------------------------------ --- 8.9/9.9 MB 236.1 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 236.1 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 236.1 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 236.1 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 236.1 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 236.1 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 236.1 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 236.1 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 236.1 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 236.1 kB/s eta 0:00:05
   ------------------------------------- -- 9.2/9.9 MB 232.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 232.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 232.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 232.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 232.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 232.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 232.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 232.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 232.8 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 232.8 kB/s eta 0:00:03
   -------------------------------------- - 9.4/9.9 MB 226.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 226.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 226.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 226.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 226.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 226.7 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 226.7 kB/s eta 0:00:02
   ---------------------------------------  9.7/9.9 MB 224.4 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 224.4 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 224.4 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 224.4 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 224.4 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 235.0 kB/s  0:00:46
Installing collected packages: pandas
Successfully installed pandas-3.0.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [18]:
d = {'names': ['A','B','C','D'], 'age': [15,26,35,25],'mobile':[2154,2254,4531,2145]}

In [19]:
d

{'names': ['A', 'B', 'C', 'D'],
 'age': [15, 26, 35, 25],
 'mobile': [2154, 2254, 4531, 2145]}

In [21]:
st_data = pd.DataFrame(d)

In [22]:
st_data

  names  age  mobile
0     A   15    2154
1     B   26    2254
2     C   35    4531
3     D   25    2145

In [23]:
st_data.to_csv('students_data.csv')

# Loading data

In [26]:
insurance_data = pd.read_csv('insurance_data.csv')

In [27]:
insurance_data

    age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [29]:
data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv')

In [30]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [32]:
data.size

10692

In [33]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [35]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [36]:
data.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

In [39]:
data.size

10692

In [40]:
data['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [41]:
data['Age'].mean()

np.float64(29.69911764705882)

In [44]:
data['Age'].median()

np.float64(28.0)

In [45]:
data['Age'].sum()

np.float64(21205.17)

In [46]:
data[['Age','Name']]

      Age                                               Name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
886  27.0                              Montvila, Rev. Juozas
887  19.0                       Graham, Miss. Margaret Edith
888   NaN           Johnston, Miss. Catherine Helen "Carrie"
889  26.0                              Behr, Mr. Karl Howell
890  32.0                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [49]:
data[['Name','Survived','Fare']]

                                                  Name  Survived     Fare
0                              Braund, Mr. Owen Harris         0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...         1  71.2833
2                               Heikkinen, Miss. Laina         1   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)         1  53.1000
4                             Allen, Mr. William Henry         0   8.0500
..                                                 ...       ...      ...
886                              Montvila, Rev. Juozas         0  13.0000
887                       Graham, Miss. Margaret Edith         1  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"         0  23.4500
889                              Behr, Mr. Karl Howell         1  30.0000
890                                Dooley, Mr. Patrick         0   7.7500

[891 rows x 3 columns]

In [51]:
data['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [52]:
data['Age'] > 50

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [59]:
data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv')

In [60]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [61]:
data[data['Age'] > 50 ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
...,...,...,...,...,...,...,...,...,...,...,...,...
820,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gr...",female,52.0,1,1,12749,93.5000,B69,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [62]:
 data[['Age','Fare']]  > 50

       Age   Fare
0    False  False
1    False   True
2    False  False
3    False   True
4    False  False
..     ...    ...
886  False  False
887  False  False
888  False  False
889  False  False
890  False  False

[891 rows x 2 columns]

In [63]:
data[data['Fare']> 100]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss. Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

In [64]:
data['Fare'] == 0

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [66]:
data[data['Fare'] == 0 ]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0,NaN,S
263,264,0,1,"Harrison, Mr. William",male,40.0,0,0,112059,0.0,B94,S
271,272,1,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0,NaN,S
277,278,0,2,"Parkes, Mr. Francis ""Frank""",male,NaN,0,0,239853,0.0,NaN,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0,NaN,S
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0,NaN,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S
597,598,0,3,"Johnson, Mr. Alfred",male,49.0,0,0,LINE,0.0,NaN,S
633,634,0,1,"Parr, Mr. William Henry Marsh",male,NaN,0,0,112052,0.0,NaN,S
674,675,0,2,"Watson, Mr. Ennis Hastings",male,NaN,0,0,239856,0.0,NaN,S
732,733,0,2,"Knight, Mr. Robert J",male,NaN,0,0,239855,0.0,NaN,S
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0,A36,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0,B102,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0,NaN,S

In [67]:
data['Fare'].max()

np.float64(512.3292)

In [68]:
data[data['Fare'] == 512.3292]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [72]:
data['Sex'] == 'male'

0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Name: Sex, Length: 891, dtype: bool

In [73]:
data[data['Sex'] == 'male']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [74]:
data[data['Sex'] == 'male'].size

6924

In [75]:
891 - 577

314

In [76]:
data[data['Sex'] == 'female']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

survived ---? 342
dead ---? 549

In [77]:
data[data['Survived'] == 1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [78]:
data[data['Survived'] == 0]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# Survived & Sex
size males ---> Total 577
size females ---> Total 314

male ---> sur? 577
male ---> dead? 468

females ---> sur? 233
females ---> dead? 81

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv')

In [4]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
data[(data['Sex'] == 'male') & (data['Survived'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [9]:
577-109

468

In [10]:
data[(data['Sex'] == 'male') & (data['Survived'] == 0)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
(468/577)*100

81.10918544194108

In [12]:
print(f'Percentage of males who dead is {(468/577)*100}')

Percentage of males who dead is 81.10918544194108

In [24]:
print(f'Percentage of males who Survived is {(109/577)*100}')

Percentage of males who Survived is 18.890814558058924

In [15]:
#females

In [16]:
data[(data['Sex'] == 'female') & (data['Survived'] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [18]:
314 - 233

81

In [19]:
data[(data['Sex'] == 'female') & (data['Survived'] == 0)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
854,855,0,2,"Carter, Mrs. Ernest Courtenay (Lilian Hughes)",female,44.0,1,0,244252,26.0000,NaN,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [22]:
print(f'Percentage of females who dead is {(81/314)*100}')

Percentage of females who dead is 25.796178343949045

In [23]:
print(f'Percentage of males who Survived is {(233/314)*100}')

Percentage of males who Survived is 74.20382165605095